[package]
name = "ntmusic_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
memmap2 = "0.9"
napi = { version = "2", default-features = false, features = ["napi6", "tokio_rt"] }
napi-derive = "2"
ntmusic_engine = { path = "../ntmusic_engine" }

[build-dependencies]
napi-build = "2"
